# _config.yml
title: "W3C Hackathon TPAC 2025 — Kobe, November 11"
description: "Register now for an evening of quick prototyping, fresh ideas, and nerdy prizes."
markdown: kramdown
theme: null
sass:
  style: compressed
baseurl: /2025/11/TPAC/hackathon/
