# _config.yml
title: "W3C Hackathon TPAC 2025 — Kobe"
description: "Build a tiny web demo or propose a community tool idea."
markdown: kramdown
theme: null
sass:
  style: compressed
baseurl: https://www.w3.org/2025/11/TPAC/hackathon/
